version: '3.8'

services:
  web:
    image: ${DOCKER_REGISTRY-}mesalisto
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Host=ep-long-pine-a4e19dq9-pooler.us-east-1.aws.neon.tech;Username=neondb_owner;Password=npg_3l0yHtThsLVp;Database=neondb;SSL Mode=Require;Trust Server Certificate=true;
